name: Test Build

on: [workflow_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACE_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACE_SECRET_KEY}}
  PLAUSIBLE_URL: ${{ secrets.PLAUSIBLE_URL }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  GOPRIVATE: github.com/slingdata-io/*
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build-brew:
    runs-on: [self-hosted-mac]
    timeout-minutes: 20
    # runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.24.6"
          cache: false
        
      - name: Load Secrets
        uses: flarco/infisical-action@v2
        with:
          version: 0.28.1
          client_id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client_secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          use_system_python: true
        
      - name: Prep for build
        run: bash scripts/ci/prep.mac.sh

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: build --clean --skip=validate -f .goreleaser.mac.yaml

      - name: Post Tests
        run: |
          dist/sling_darwin_arm64/sling conns discover local -p '.'

  build-scoop:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.24.6"
          cache: true
        
      - name: Load Secrets
        uses: flarco/infisical-action@v2
        with:
          version: 0.28.1
          client_id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client_secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          use_system_python: true

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"
        
      - name: Prep for build
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"

          .\scripts\ci\prep.win.ps1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: build --clean --skip=validate -f .goreleaser.windows.yaml

      - name: Post Tests
        shell: pwsh
        run: |
          .\dist\sling_windows_amd64_v1\sling.exe conns discover local -p '.'

  build-linux-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.24.6"
          cache: false
        
      - name: Load Secrets
        uses: flarco/infisical-action@v2
        with:
          version: 0.28.1
          client_id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client_secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          use_system_python: true

      - name: Login docker
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u slingdata --password-stdin
        
      - name: Prep for build
        run: bash scripts/ci/prep.linux.sh

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: build --clean --skip=validate -f .goreleaser.linux.arm64.yaml

      - name: Post Tests
        run: |
          dist/sling_linux_arm64/sling conns discover local -p '.'

  build-linux-amd64:
    # runs-on: ubuntu-20.04
    runs-on: [self-hosted, Linux, X64, ubuntu-16]
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.24.6"
          cache: false
        
      - name: Load Secrets
        uses: flarco/infisical-action@v2
        with:
          version: 0.28.1
          client_id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client_secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          use_system_python: true

      - name: Login docker
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u slingdata --password-stdin
        
      - name: Prep for build
        run: bash scripts/ci/prep.linux.sh

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: build --clean --skip=validate -f .goreleaser.linux.amd64.yaml

      - name: Post Tests
        run: |
          dist/sling_linux_amd64_v1/sling conns discover local -p '.'